mozilla/tls-canary

main.py
url_store.py

The new command line option limits the number of URLs processed from
a URL store.
This addresses https://github.com/cr/tls-canary/issues/18

Adding "--limit" parameter

---

README.md
linux_bootstrap.sh
main.py
one_crl_downloader.py

Moving from manual package installation via git to using the package
handling provided by the go binary.

Improving OneCRL Go package handling

---

js/scan_url.js

All paths passed to our JS script do not have trailing slashes, so let's keep it that way. Instead, I modified the best place in the JS file to add the trailing slash in this case, in order to allow SSL certificate saving to work again.

Fixing cert saving issue - path needed trailing slash

---

main.py
one_crl_downloader.py

Currently it re-downloads revocations.txt on every run although it hardly changes frequently.

Accelerate one_crl_downloader.py by caching and add Windows support

---

README.md
main.py
one_crl_downloader.py
setup.py

* Adapting to upstream parameter changes in onecrl package
* Go package updates now work as intended
* Version bump to 3.0.1

OneCRL bugfix release

---

firefox_app.py

This is a trivial fix for #54. This PR replaces the PR
from the misnamed branch in #70.

Looking for *.app instead of Firefox*.app in OSX pkg

---

README.md
hooks/pre-commit
requirements.txt

* It can be installed by running `ln -sf ../../hooks/pre-commit .git/hooks/`
* Need to run `pip install pep8` or `pip install -e .` again after this lands.

Adding PEP8 pre-commit hook

---

README.md
setup.py
tlscanary/firefox_downloader.py
tlscanary/main.py
tlscanary/modes/basemode.py

This adds support for passing the path to local build directories and package files for the `--base` and `--test` command line arguments.
The PR is still tentative because cloning and building *mozilla-central* for testing on Linux is still ongoing. Looks like my Linux laptop will be taking a few hours for that. If anyone here has local Linux build tree around, feel free to test this branch and report the results.
This is adressing #92.

Support for testing package files and build trees

---

README.md
tlscanary/modes/basemode.py
tlscanary/modes/performance.py

This implements #99, a temporary workaround addressing #44.

Setting hosts limit default to 100k

---

setup.py
tlscanary/modes/basemode.py
tlscanary/modes/performance.py
tlscanary/one_crl_downloader.py

* Adding the `--onecrlpin` argument for pinning OneCRL-Tools, defaulting to the last known-working commit
* Internally checking out that commit before running the `go install` command
* Bumping version to 3.1.1

Pinning OneCRL-Tools to a known-working commit

---

bootstrap/linux_bootstrap.sh

This resolves that apt-get was requesting numerous user interactions during bootstrapping, and it also adds the pip package to linux installs.

Adding python-pip to and -y to apt-get bootstrap

---

tlscanary/js/scan_worker.js

This is fixing #123 preventing the XPCShell worker from switching to a new profile.

Replacing obsolete nsILocalFile with nsIFile

---

tlscanary/modes/basemode.py
tlscanary/one_crl_downloader.py

Noticed that the canary broke today. mozmark migrated the OneCRL Tools repo to the master Mozilla repo on git, so that info needed to change. Also, the default git commit needed to be updated.

OneCRL repo moved from mozmark to master mozilla git repo

---

.travis.yml

See #135 which can be closed once Linux testing is fixed and this patch reverted.

Temporarily disabling Linux testing on Travis

---

.travis.yml
tlscanary/modes/basemode.py
tlscanary/modes/regression.py
tlscanary/one_crl_downloader.py

The main scanning logic has been cleaned up and put inside a loop, which iterates based on desired amount of scans. The larger the number of scans, the lower the final error rate.
Also introduced a flag to enable content caching in test profiles, if desired. 
This PR requires changes to OneCRL from PR #130.

Improve regression mode to support configurable scans and caching

---

tlscanary/js/scan_worker.js

See issue #132 for more info. 
This is one small step to moving towards using pure JSON logs instead of the custom htmlreport.

Fixing issue 132 - missing short error string

---

tests/zz_tlscanary_integration_test.py
tlscanary/modes/basemode.py
tlscanary/modes/regression.py
tlscanary/sources/revoked.csv

This ensures that we can't run `regression` mode without verifying that the OneCRL mechanism is working. In the future, we could consider moving this to `base` mode, but we currently don't need it there.
I implemented this using a custom source file ("revoked.csv") that currently only contains one host. In the future, we can add test hosts that fit our guidelines (revoked by OneCRL, with or without OCSP) and the logic should accommodate this.

Adding OneCRL sanity test to regression mode

---

tlscanary/modes/basemode.py

Switching default OneCRL pin to 'stable' tag

---

tests/zz_tlscanary_integration_test.py
tlscanary/js/scan_worker.js
tlscanary/modes/basemode.py
tlscanary/modes/performance.py
tlscanary/modes/regression.py
tlscanary/modes/scan.py

This PR addresses three issues:
First, it fixes a regression in the integration test that was caused by removing the htmlreport legacy feature which the test depended on. The fix was to switch the test to the webreport feature.
Second, it fixes a regression caused by bug 792808 landing in nightly, removing XPCOM stuff from XHR. This caused the scan worker to produce ```TypeError: Cc['@mozilla.org/xmlextras/xmlhttprequest;1'] is undefined``` errors during scans that reduced TLSCanary to producing "Worker dropped results" warnings.
Third, it adds the ```--remove_certs``` option for preventing certificate data from clogging the logs, as requested by the NSS team in #155.

Final cleanup before 3.2 release

---

README.md
tlscanary/firefox_downloader.py
tlscanary/js/scan_worker.js
tlscanary/modes/sourceupdate.py

Firefox 63 dropped XPCOMUtils.IterSimpleEnumerator, leading to JS errors when requesting the full certificate chain.
This patch is switching JS xpcshell worker to iterating the cert chain object directly.
See http://bugzil.la/1484496 for details.

Fixing urllib import error and certificate enumeration regression

---

tlscanary/tools/xpcshell_worker.py

Fix a probable typo in the XPCShell worker where the `head_` prefix was missing and `head_script` never gets set to the the `head_script` arg.
If most uses of the XPCShell worker used the default `head_script`, then this branch might've never been used before.

tools: xpcshell worker set head_script
