- template/js/Data.js
- template/js/TLSCanary.js
- template/js/Utility.js
Convert dates from certificate fields to a generic format, which allows them to be sorted in the report UI.
> Fixing date sort bug

- main.py
- setup.py
This is the final commit for our 3.0.0 release.
Addresses issue #39
> Version bump for package and binary to 3.0.0

- .gitignore
- README.md
- firefox_downloader.py
- main.py
- setup.py
- tests/__init__.py
- windows_bootstrap.txt
* Switching PowerShell codepage to 65001
* Fixing case-insensitive path comparisons
* Adding Windows-specific documentation
> Improving Windows support

- README.md
- setup.py
- tlscanary/main.py
- tlscanary/modes/__init__.py
* Making the 'mode' argument mandatory
* Removing ipython option and dependency
* Rewording documentation
* Version bump to 3.1.0a15
> Improving usability and documentation

- tlscanary/modes/basemode.py
- tlscanary/modes/regression.py
Would like to land this soon. Should be non-invasive change.
> Fixing issue 87 - incorrect logic for custom OneCRL testing

- .gitignore
- README.md
- setup.py
- tests/__init__.py
- tests/zz_tlscanary_integration_test.py
* Covering regression, scan, srcupdate and JSON logging
I am mildly excited about this important step towards 3.1.1. Knowing how trivial it was to implement, I now think we should have had this a long time.
> Adding integration testing

- .travis.yml
- README.md
- bootstrap/bootstrap.sh
- bootstrap/osx_bootstrap.sh
> Adding Travis CI integration

- setup.py
- tests/sources_db_test.py
- tlscanary/modes/sourceupdate.py
- tlscanary/sources_db.py
This is an incremental change towards #44. Should be RTL.
> Adding centralized Sources chunking

- tlscanary/modes/performance.py
- tlscanary/modes/regression.py
- tlscanary/modes/scan.py
> Adding sources_size to log metadata

- setup.py
... for the v3.1.2 stability release.
> Bumping version to 3.1.2

- README.md
- tlscanary/modes/regression.py
Updated documentation for previous regression mode changes. 
Also, removed unneeded debugging statement.
> Improved regression mode - updated README

- tlscanary/js/scan_worker.js
Give it a look. If you like it, feel free to land it. Or if you want to tweak it, feel free.
> Replacing outdated getChain API

- tlscanary/js/scan_worker.js
> Moving nsISSLStatusProvider to nsITransportSecurityInfo

- setup.py
This is a hotfix release for issue #166 which is breaking deployments.
> Bumping to v3.2.2 for Hotfix release

- tlscanary/js/globaltest.js
- tlscanary/js/scan_worker.js
> Replacing XPCOMUtils.generateQI

- setup.py
- tlscanary/js/scan_worker.js
- tlscanary/modes/sourceupdate.py
This should fix current nightly breakage and harmonize the info structure across Firefox versions.
> Rewriting JS code for SSL state evaluation

- tlscanary/js/scan_worker.js
I have tested this locally and it works. Just wondering whether you agree it's the right approach.
> Stripping token info from AppConstants

- tlscanary/modes/log.py
- tlscanary/tags_db.py
This fixing issues #192 and #193.
> Minor fixes for log mode

- setup.py
- tlscanary/scheduler/main.py
- tlscanary/scheduler/matplotlib_agg.py
Can be used via `pip install .[scheduler]` or `pip install .[dev]`. The scheduler script is called `tlscscheduler` and requires the path to its output directory as first and only argument.
> Adding plot scheduler

- tlscanary/modes/basemode.py
- tlscanary/tools/one_crl_downloader.py
one_crl_to_cert_storage was failing on subejct / publicKeyPair OneCRL entries. Also, clean installations (without existing profile data) were failing
Fixes issue 222
> fixed outstanding OneCRL-Tools issues

- Dockerfile
Might want to rename or move it to something with ubuntu in the filename if supporting multiple OSes is important.
Example usage:
```console
~/tls-canary » docker build -t tlscanary:latest .
... grab coffee ...
~/tls-canary » mkdir -p cache
~/tls-canary » docker run -v "$(pwd)/cache:/root/.tlscanary/cache" -it tlscanary:latest --debug regression --source top --onecrlpin origin/main -l 5
[32m2020-09-23 17:17:44[0m [1;30mDEBUG[0m MainThread [34mtlscanary.main[0m [32mCommand arguments: Namespace(base='release', cache=False, debug=True, filter=1, limit=5, max_timeout=20, mode='regression', onecrl='production', onecrlpin='origin/main', parallel=4, prefs=None, prefs_base=None, prefs_test=None, remove_certs=False, requestsperworker=50, scans=3, source='top', test='nightly', timeout=10, …
```
> add dockerfile for bootstrapped ubuntu:20.04

- tlscanary/modes/basemode.py
Every time I come to the Canary I fight with how to set prefs. So here's documentation in-code of how they work. :)
> Add clarification to how prefs work
